name: CICD Harbor
on:
  push:
    branches:
      - feature/*
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    branches:
      - main
      - develop
      - staging
jobs:
  build:
    uses: devfrensh/cicd-templates/.github/workflows/npm.yml@main
    secrets: inherit
  sonar:
    uses: devfrensh/cicd-templates/.github/workflows/sonar.yml@main
    secrets: inherit
    needs: build
  registry:
    uses: devfrensh/cicd-templates/.github/workflows/registryHarbor.yml@main
    secrets: inherit
    needs: sonar