name: CICD Harbor
on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      repo:                 # <- NUEVO
        type: string
        required: true
  push:
    branches:
      - feature/*
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    branches:
      - main
      - develop
      - staging
jobs:
  build:
    uses: devfrensh/cicd-templates/.github/workflows/npm.yml@main
    secrets: inherit
  sonar:
    uses: devfrensh/cicd-templates/.github/workflows/sonar.yml@main
    secrets: inherit
    needs: build
  registry:
    needs: sonar
    permissions:
      contents: read
      packages: write
    uses: devfrensh/cicd-templates/.github/workflows/registryGhcr.yml@main
    with:
      image: ghcr.io/${{ github.repository }}
      context: .
    secrets: inherit