name: Dependency Install
on:
 workflow_call:
jobs:
 dependency:
   runs-on: [self-hosted, linux, x64, wsl-linux]
   permissions:
     contents: read
   environment: ${{ github.ref_name }}
   steps:
     - uses: actions/checkout@v4
     - name: Check Node/npm available (fail fast)
       run: |
         set -e
         echo "Node: $(node -v)"
         echo "npm:  $(npm -v)"
     - name: Install dependencies
       run: npm ci --no-audit --no-fund