name: Reusable - Build & Push to Harbor (only develop)
on:
 workflow_call:
   inputs:
     extra_tags:
       type: string
       required: false
       default: ""
jobs:
 push:
   # Solo corre en develop (evita rebuilds en staging/main)
   if: github.ref_name == 'develop'
   name: Harbor / Build & Push (DEV)
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: read
   env:
     REGISTRY:   ${{ vars.HARBOR_REGISTRY }}
     REPO_NAME:  ${{ github.event.repository.name }}
     BRANCH:     ${{ github.ref_name }}
     SHA:        ${{ github.sha }}
     # Solo DEV: el promote se encarga de STG/PROD
     PROJ_DEV:   ${{ vars.HARBOR_PROJECT_DEVELOP || vars.HARBOR_PROJECT_DEV || vars.HARBOR_PROJECT }}
   steps:
     - uses: actions/checkout@v4
     - uses: docker/setup-qemu-action@v3
     - uses: docker/setup-buildx-action@v3
     - name: Derive image & tags (DEV only)
       id: meta
       shell: bash
       run: |
         set -euo pipefail
         [ -n "${REGISTRY}" ] || { echo "Falta vars.HARBOR_REGISTRY"; exit 1; }
         [ -n "${PROJ_DEV}" ] || { echo "Falta HARBOR_PROJECT_DEVELOP/DEV/HARBOR_PROJECT"; exit 1; }
         # nombre imagen = nombre del repo (saneado)
         IMG="$(echo "${REPO_NAME}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g')"
         # tags base (siempre SHA)
         TAGS="${REGISTRY}/${PROJ_DEV}/${IMG}:${SHA}"
         # fuente de la promoción
         TAGS="${TAGS},${REGISTRY}/${PROJ_DEV}/${IMG}:develop"
         # tags extra opcionales (en DEV)
         if [ -n "${{ inputs.extra_tags }}" ]; then
           IFS=',' read -ra arr <<< "${{ inputs.extra_tags }}"
           for t in "${arr[@]}"; do
             t="$(echo "$t" | xargs)"; [ -z "$t" ] && continue
             TAGS="${TAGS},${REGISTRY}/${PROJ_DEV}/${IMG}:$t"
           done
         fi
         echo "img=${IMG}"         >> "$GITHUB_OUTPUT"
         echo "tags=${TAGS}"       >> "$GITHUB_OUTPUT"
         echo "Destino (DEV):"
         echo "$TAGS" | tr ',' '\n'
     # Secrets por ambiente (DEV)
     - name: Login to Harbor (DEV)
       uses: docker/login-action@v3
       with:
         registry:  ${{ env.REGISTRY }}
         username:  ${{ secrets.HARBOR_USERNAME_DEV }}
         password:  ${{ secrets.HARBOR_PASSWORD_DEV }}
     - name: Build & Push (DEV)
       id: bp
       uses: docker/build-push-action@v6
       with:
         context: .
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         provenance: false
         cache-from: type=gha
         cache-to:   type=gha,mode=max
     - name: Show pushed digest & tags
       run: |
         echo "Pushed tags:"
         echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'
         # El digest lo imprime buildx en logs; si quieres guardarlo:
         # crane digest "$FIRST_TAG"