name: Reusable - Build & Push to Harbor (auto-map)
on:
 workflow_call:
   inputs:
     extra_tags:
       type: string
       required: false
       default: ""
   secrets:
     HARBOR_USERNAME:
       required: true
     HARBOR_PASSWORD:
       required: true
jobs:
 push:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: read
   env:
     REGISTRY:  ${{ vars.HARBOR_REGISTRY }}
     REPO_NAME: ${{ github.event.repository.name }}
     BRANCH:    ${{ github.ref_name }}
     SHA:       ${{ github.sha }}
     PROJ_DEV:  ${{ vars.HARBOR_PROJECT_DEVELOP }}
     PROJ_STG:  ${{ vars.HARBOR_PROJECT_STAGING }}
     PROJ_PROD: ${{ vars.HARBOR_PROJECT_PROD }}
   steps:
     - uses: actions/checkout@v4
     - uses: docker/setup-qemu-action@v3
     - uses: docker/setup-buildx-action@v3
     - name: Derive project, image & tags
       id: meta
       shell: bash
       run: |
         # elegir proyecto por rama
         case "${BRANCH}" in
           develop) PROJECT="${PROJ_DEV}" ;;
           staging) PROJECT="${PROJ_STG}" ;;
           main)    PROJECT="${PROJ_PROD}" ;;
           *)       PROJECT="${PROJ_DEV}" ;;
         esac
         [ -n "${REGISTRY}" ] || { echo "Falta vars.HARBOR_REGISTRY"; exit 1; }
         [ -n "${PROJECT}"  ] || { echo "Falta alguna vars.HARBOR_PROJECT_*"; exit 1; }
         # nombre imagen = nombre del repo, saneado
         IMG="$(echo "${REPO_NAME}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g')"
         BR="$(echo "${BRANCH}"    | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g')"
         # tags: sha + branch (+ latest en main)
         TAGS="${REGISTRY}/${PROJECT}/${IMG}:${SHA},${REGISTRY}/${PROJECT}/${IMG}:${BR}"
         [ "${BRANCH}" = "main" ] && TAGS="${TAGS},${REGISTRY}/${PROJECT}/${IMG}:latest"
         # extra tags opcionales
         if [ -n "${{ inputs.extra_tags }}" ]; then
           IFS=',' read -ra arr <<< "${{ inputs.extra_tags }}"
           for t in "${arr[@]}"; do
             t=$(echo "$t" | xargs)
             [ -z "$t" ] || TAGS="${TAGS},${REGISTRY}/${PROJECT}/${IMG}:$t"
           done
         fi
         echo "tags=$TAGS" >> $GITHUB_OUTPUT
         echo "Destino:"
         echo "$TAGS" | tr ',' '\n'
     - name: Login to Harbor
       uses: docker/login-action@v3
       with:
         registry: ${{ env.REGISTRY }}
         username: ${{ secrets.HARBOR_USERNAME }}
         password: ${{ secrets.HARBOR_PASSWORD }}
     - name: Build & Push
       uses: docker/build-push-action@v6
       with:
         context: .
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         provenance: false