name: Registry Harbor Container
on:
 workflow_call:
   inputs:
     image_name:
       description: app
       type: string
       required: true
     registry:
       description: demo.goharbor.io o harbor.local
       type: string
       required: true
     project:
       description: prototype-ntt
       type: string
       required: true
     tag_extra:
       type: string
       required: false
       default: latest
   secrets:
     HARBOR_USERNAME:
       required: true   # robot$<...>
     HARBOR_PASSWORD:
       required: true   # token del robot
jobs:
 push:
   runs-on: ${{ inputs.registry == 'harbor.local' && 'self-hosted' || 'ubuntu-latest' }}
   permissions:
     contents: read
     packages: read
   steps:
     - uses: actions/checkout@v4
     - uses: docker/setup-qemu-action@v3
     - uses: docker/setup-buildx-action@v3
     - name: Login to Harbor
       uses: docker/login-action@v3
       with:
         registry: ${{ inputs.registry }}
         username: ${{ secrets.HARBOR_USERNAME }}
         password: ${{ secrets.HARBOR_PASSWORD }}
     - name: Build & Push
       uses: docker/build-push-action@v6
       with:
         context: .
         push: true
         tags: |
           ${{ inputs.registry }}/${{ inputs.project }}/${{ inputs.image_name }}:${{ github.sha }}
           ${{ inputs.tag_extra && format('{0}/{1}/{2}:{3}', inputs.registry, inputs.project, inputs.image_name, inputs.tag_extra) || '' }}
         provenance: false