name: Registry GHCR
on:
 workflow_call:
   inputs:
     image:            # ej: ghcr.io/OWNER/REPO
       type: string
       required: true
     context:
       type: string
       required: false
       default: .
   secrets:
     GITHUB_TOKEN:
       required: true
jobs:
 build-and-push-image:
   runs-on: ubuntu-latest
   # 👈 ÚNICO CAMBIO IMPRESCINDIBLE (para GHCR)
   permissions:
     contents: read
     packages: write   # necesario para publicar en GHCR
   steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Login to GHCR
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Extract metadata (tags, labels)
       id: meta
       uses: docker/metadata-action@v5
       with:
         images: ${{ inputs.image }}
         tags: |
           type=raw,value=${{ github.sha }}
           type=ref,event=branch
           type=ref,event=tag
     - name: Build and push
       uses: docker/build-push-action@v6
       with:
         context: ${{ inputs.context }}
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}