name: Reusable - Build & Push to Harbor (auto)
on:
 workflow_call:
   inputs:
     extra_tags:
       description: "Tags adicionales separados por coma (opcional)"
       type: string
       required: false
       default: ""
   secrets:
     HARBOR_USERNAME:
       required: true
     HARBOR_PASSWORD:
       required: true
jobs:
 push:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: read
   # REGISTRY viene como variable de repo/org.
   # PROJECT viene del Environment del caller (vars.HARBOR_PROJECT).
   env:
     REGISTRY:  ${{ vars.HARBOR_REGISTRY }}
     PROJECT:   ${{ vars.HARBOR_PROJECT }}
     REPO_NAME: ${{ github.event.repository.name }}
     BRANCH:    ${{ github.ref_name }}
     SHA:       ${{ github.sha }}
   steps:
     - uses: actions/checkout@v4
     - uses: docker/setup-qemu-action@v3
     - uses: docker/setup-buildx-action@v3
     - name: Derive image & tags (auto)
       id: meta
       shell: bash
       run: |
         # image_name = nombre del repo, minúsculas y saneado
         IMG="$(echo "${REPO_NAME}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g')"
         BR="$(echo "${BRANCH}"    | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g')"
         # validaciones
         [ -n "${REGISTRY}" ] || { echo "Falta vars.HARBOR_REGISTRY"; exit 1; }
         [ -n "${PROJECT}"  ] || { echo "Falta vars.HARBOR_PROJECT (variable del Environment)"; exit 1; }
         # tags por defecto: sha + branch (+ latest en main)
         TAGS="${REGISTRY}/${PROJECT}/${IMG}:${SHA},${REGISTRY}/${PROJECT}/${IMG}:${BR}"
         if [ "${BRANCH}" = "main" ]; then
           TAGS="${TAGS},${REGISTRY}/${PROJECT}/${IMG}:latest"
         fi
         # extra tags opcionales (coma-separado)
         if [ -n "${{ inputs.extra_tags }}" ]; then
           IFS=',' read -ra arr <<< "${{ inputs.extra_tags }}"
           for t in "${arr[@]}"; do
             t=$(echo "$t" | xargs)
             [ -z "$t" ] || TAGS="${TAGS},${REGISTRY}/${PROJECT}/${IMG}:$t"
           done
         fi
         echo "image=$IMG"  >> $GITHUB_OUTPUT
         echo "tags=$TAGS"  >> $GITHUB_OUTPUT
         echo "Publicaré:"
         echo "$TAGS" | tr ',' '\n'
     - name: Login to Harbor
       uses: docker/login-action@v3
       with:
         registry: ${{ env.REGISTRY }}
         username: ${{ secrets.HARBOR_USERNAME }}
         password: ${{ secrets.HARBOR_PASSWORD }}
     - name: Build & Push
       uses: docker/build-push-action@v6
       with:
         context: .
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         provenance: false